#pragma once

#define APPS_1_PIN 0
#define APPS_2_PIN 0

#define APPS_1_UPPER_BOUND 0
#define APPS_1_LOWER_BOUND 0

#define APPS_2_UPPER_BOUND 0
#define APPS_2_LOWER_BOUND 0

#define APPS1_DEAD_THRESHOLD 0
#define APPS2_DEAD_THRESHOLD 0

#define APPS1_DEADZONE_EQUIVALENT 0
#define APPS2_DEADZONE_EQUIVALENT 0

#define APPS_LINEAR_OFFSET 0

#define APPS_MAX 0
#define APPS_MIN 0

#define APPS_MAX_ERROR_PERCENT (0)
#define APPS_MAX_ERROR_ABS (APPS_1_UPPER_BOUND * APPS_MAX_ERROR_PERCENT / 100)

#define APPS_SAMPLES 5

#define APPS_BLOCK_THRESHOLD 0
#define APPS_IMPLAUSIBLE_TIMEOUT_MS 0
#define APPS_BRAKE_PLAUSIBILITY_TIMEOUT_MS 0

#define BUZZER_PIN 0
#define FRONT_RIGHT_WHEEL_ENCODER_PIN 0
#define FRONT_LEFT_WHEEL_ENCODER_PIN 0
#define LIMIT_RPM_INTERVAL 500000
#define WPS_PULSES_PER_ROTATION 36